name = []
print(name)
name.append('Рома')
print (name)
name.append('Илья')
print (name)
name.append('Артем')
print (name)
name.append('Юля')
print (name)
name.append('Артемий')
print (name)
name.append('Ярик')
print (name)
name.append('Стас')
print (name)
name.append('Леша')
print (name)
name.append('Илюша')
print(name)
name.remove('Илюша')
print(name)
name.remove('Леша')
print(name)
name.remove('Стас')
print(name)
name.remove('Ярик')
print(name)
name.remove('Артемий')
print(name)
name.remove('Юля')
print(name)
name.remove('Артем')
print(name)
name.remove('Илья')
print(name)
name.remove('Рома')
print(name)


